### ISSUE TITLE
Cannot Open WhatsApp on Injected Chrome

### ISSUE THREAD

**Issue by soulhd** [Flareonz44/WhatsApp-Web-Session-Dumper#1]
Hi,
I'm using this script on target PC with:
Google Chrome v. 103.0.5060.114 (Official Build) (64-bit) running on Windows 10 Pro 21H2
and WhatsApp v. 2.22.14.74 running on Android 10 mobile phone.

I'm able to dump WhatsApp session from source PC and successfully injected it into target PC, but  then the target PC cannot connect to WhatsApp with a message like this:
![image](https://user-images.githubusercontent.com/2696663/178614998-40918500-1d9e-4a5d-b6c6-802fe3aeea67.png)

Any suggestion what could be the problem?

**Comment by hamzos** [comment]
Hello @soulhd 
I'm experiencing the exact same issue.
Please let me know if you find any solution.
Thanks

**Comment by Flareonz44** [comment]
@soulhd @hamzos 
Hello,
Thanks for using my script :)
I just made a test and you both are right, the script isn't working. Look, the script is actually very simple as it only dumps the token keys and other data on a file, and the injector only replaces the tokens and access keys on local storage on Chrome browser, so it's like "cloning tabs". The problem could be either latest chrome versions or whatsapp web libraries. If the libraries are the problem, I'm afraid that this script is obsolete.
I will take a look anyway.

**Comment by Evolgate** [comment]
Any update?

**Comment by Flareonz44** [comment]
I've been making a lot of test, but no one works. This tool is deprecated for Whatsapp Web. If you wish, you can test it on other platforms.

**Comment by Flareonz44** [comment]
I've been making a lot of test, but no one works. This tool is deprecated for Whatsapp Web. If you wish, you can test it on other platforms.

**Comment by Flareonz44** [comment]
I've been making a lot of test, but no one works. This tool is deprecated for Whatsapp Web. If you wish, you can test it on other platforms.
